{{- if .Values.default.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}-adserver-ingress
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  rules:
  - host: {{ .Values.default.domain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.default.serviceName }}
          servicePort: {{ .Values.default.servicePort}}
{{- end }}
